-- Using the NYC Taxi public dataset (Yellow Trips) from Google BigQuery, complete the following exercises:
-- bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022

-- Exercise 1: Count the number of trips in January 2022
SELECT COUNT(passenger_count)
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
WHERE data_file_month = 1;

-- Exercise 2: Calculate the total revenue generated by taxi trips in 2022
SELECT SUM(total_amount - (imp_surcharge + airport_fee)) AS total_revenue
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022;

-- Exercise 3: Find the most popular pickup location
SELECT COUNT(*) as num_trips
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
GROUP BY pickup_location_id
ORDER BY num_trips DESC
LIMIT 1;

-- Exercise 4: Analyze the number of trips per hour of the day
SELECT EXTRACT(HOUR FROM pickup_datetime) AS hour, COUNT (*) AS num_trips
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
GROUP BY hour
ORDER BY num_trips DESC;

-- Exercise 5: Calculate the average trip distance
SELECT AVG(trip_distance) AS avg_distance
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022;

-- Exercise 6: Find the longest trip by distance
SELECT *
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
ORDER BY trip_distance DESC
LIMIT 1;

-- Exercise 7: Calculate the total number of passengers by payment type
SELECT payment_type, SUM(passenger_count) as num_pass
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
GROUP BY payment_type
ORDER BY num_pass DESC;

-- Exercise 8: Find the most common drop-off location for trips paid by credit card (1)
SELECT payment_type, COUNT(dropoff_location_id) AS drop_off
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
GROUP BY payment_type
HAVING payment_type = "1"
ORDER BY drop_off DESC;

-- Exercise 9: Calculate the total number of trips that had more than 4 passengers
SELECT *
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
WHERE passenger_count > 4
ORDER BY passenger_count DESC;

-- Exercise 10: Subquery - Find the average fare for trips longer than the average trip distance
SELECT AVG(fare_amount) as avg_fare, trip_distance
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
WHERE trip_distance > (SELECT AVG(trip_distance)
                      FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022)
GROUP BY trip_distance
ORDER BY trip_distance;